# Generated by Django 4.0.5 on 2022-07-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_recepeint_message_recepient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
